### ISSUE TITLE
No se crea la lista

### ISSUE THREAD

**Issue by angelmarcosmartin** [igorrecioh/movistar_M3u#1]
Hola,

En MacOSX,
El primer paso lo hace bien y devuelve el terminal.

En el segundo paso da este error:

sudo python pruebas.py

Traceback (most recent call last):
  File "pruebas.py", line 7, in <module>
    tree = ET.parse('raw_239.0.2.168_2_0.xml')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: 'raw_239.0.2.168_2_0.xml'

**Comment by igorrecioh** [comment]
Hola @angelmarcosmartin!

¿Estás en la Comunidad Autónoma Vasca? Esto es importante porque el script solo funciona en ese caso sin necesidad de modificarlo. Si no es el caso, dime desde qué Comunidad Autónoma estás ejecutándolo y te proporciono instrucciones para hacerlo correctamente.

Si efectivamente estás en la CAV, revisa que tras ejecutar ```sudo python get_xmls.py 239.0.2.168``` se ha creado un fichero raw_239.0.2.168_2_0.xml en la misma carpeta donde has ejecutado el comando. Si no se creado tal fichero, dime si se ha creado otro diferente.

Saludos!

**Comment by angelmarcosmartin** [comment]
No, soy de la Comunidad de Castilla y León (Valladolid capital)

**Comment by igorrecioh** [comment]
@angelmarcosmartin  de acuerdo, tendremos que buscar entonces la IP para Castilla y León. A ver si la puedo encontrar y te escribo. No dispongo de Movistar+ Fibra y por tanto estoy limitado en cuanto a pruebas, pero te mantengo informado!

**Comment by angelmarcosmartin** [comment]
Gracias, quedo a la espera de tu contestación a lo largo de los próximos días. Estoy pendiente de este chat para cualquier dato que necesites que te facilite. ¡Hasta luego ...!

**Comment by angelmarcosmartin** [comment]
Buenas Noches,

En un pasado proyecto para crear un desco virtual de Movistar+ hay una consulta en relacción de las IPs de las provincias. Se listan 17 IPs, que se deberían corresponder con cada una de las Comunidades Autómomas. Sólo se identifica Madrid (añado la identificación de la que ya sabemos, Pais Vasco):

239.0.2.140
239.0.2.142
239.0.2.144
239.0.2.146
239.0.2.148
239.0.2.150
239.0.2.152
239.0.2.154 - Comunidad de Madrid
239.0.2.156
239.0.2.158
239.0.2.160
239.0.2.162
239.0.2.164
239.0.2.166
239.0.2.168 - Pais Vasco
239.0.2.170
239.0.2.172

A ver si con eso te resulta más fácil identificar la correspondiente a Castilla y León.

En todo caso sería ir probando una a una hasta dar con que funciona, con los comandos UNIX, y editando la sexta linea del archivo pruebas.py poniendo la IP que estamos probando, con cada nuevo intento. ¿Sería así cómo proceder?

La página donde encontré esta información es esta:

https://sourceforge.net/p/movistartv/discussion/general/thread/180deb2b/

**Comment by igorrecioh** [comment]
Hola @angelmarcosmartin. Eso es, se puede ir probando como comentas hasta saber cuál es la correspondiente a CyL. A ver si hay suerte!

**Comment by angelmarcosmartin** [comment]
Ya he probado con todas. No ha habido suerte, en ningún caso crea el archivo raw_239.0.2.162_2_0.xml, por ejemplo.
Pero crea otro archivo en la carpeta de ejecución: tva.pyc. Con un icono del archivo un poco ensombrecido respecto a los otros tres que están inicialmente en la carpeta. Lo abro con textedit. Es un poco largo te lo pego a continuación comprimido zip. A ver si poco a poco podemos sacar algo.

[tva.pyc.zip](https://github.com/igorrecioh/movistar_M3u/files/15217598/tva.pyc.zip)

**Comment by igorrecioh** [comment]
Buenas @angelmarcosmartin. Los ficheros .pyc son compilados de Python, en este caso no nos aporta valor. Dado lo que me cuentas, va a haber que investigar un poco más. Ahora yo no tengo opción de pruebas porque no tengo a mano una conexión de fibra con Movistar y TV. En cuanto pueda llevar a cabo las pruebas te aviso a ver si consigo extraer correctamente el fichero deseado.
